version: "3.9"

services:
    php:
        build: ./docker/php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/php-fpm.conf.sh:/usr/local/etc/php-fpm.d/custom.conf
    nginx:
        image: nginx:1.21.6-alpine
        links:
            - php
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
    db:
        image: mariadb:10
        ports:
            - "3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: fat_nerd
        volumes:
            - .data/db:/var/lib/mysql
